import { Metadata } from 'next'
import './globals.css'
import { Inter } from 'next/font/google'
import Header from '../components/Header/Header'
import styles from './layout.module.scss'
import Footer from '../components/Footer/Footer'
import { Providers } from '../components/Providers/Providers'
import ModalWindows from '../components/ModalWindows/ModalWindows'
import SignupWindows from '../components/AlertWindows/SignupWindow'
import SigninWindows from '../components/AlertWindows/SigninWindow'
import LogoutWindows from '../components/AlertWindows/LogoutWindow'
import ReviewAddWindow from '../components/AlertWindows/ReviewAddWindow'
import ReviewDeleteWindow from '../components/AlertWindows/ReviewDeleteWindow'
import NotActivatedWindow from '../components/AlertWindows/NotActivated'
import MaxComparedWindow from '../components/AlertWindows/MaxCompared'
import FavoriteAddWindow from '../components/AlertWindows/FavoriteAddWindow'
import ComparedAddWindow from '../components/AlertWindows/ComparedAddWindow'
import Menu from '../components/Menu/Menu'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',  
}

export default function RootLayout({children,}: {children: React.ReactNode}){
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Menu/>
          <ModalWindows/>
          <Header/>
          <div className={styles.general_container}>
            {children}
          </div>
          <Footer/>
          {/* Всплывающие окна */}
          <ComparedAddWindow/>
          <FavoriteAddWindow/>
          <SignupWindows/>
          <SigninWindows/>
          <LogoutWindows/>
          <ReviewAddWindow/>
          <ReviewDeleteWindow/>
          <NotActivatedWindow/>
          <MaxComparedWindow/>
        </Providers>
      </body>    
    </html>
  )
}
